[tool.poetry]
name = "aula17-bootcamp"
version = "0.1.0"
description = ""
authors = ["Caio Souza <caiohas.2908@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.41"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
